ALTER TABLE "Table" ADD COLUMN IF NOT EXISTS "startingJetonsPerPlayerMillis" BIGINT NOT NULL DEFAULT 100000;
ALTER TABLE "TableMember" ADD COLUMN IF NOT EXISTS "startingJetonsCredited" BOOLEAN NOT NULL DEFAULT false;
