import { readFileSync } from "node:fs";
import { join } from "node:path";
import { expect, test } from "vitest";

test("classic tokens define one emerald, felt, cream, gold and black dock", () => {
  const tokens = readFileSync(join(process.cwd(), "src/ui/skins/classic/tokens.css"), "utf8");
  expect(tokens).toContain("--emerald:");
  expect(tokens).toContain("--felt:");
  expect(tokens).toContain("--cream:");
  expect(tokens).toContain("--gold:");
  expect(tokens).toContain("--control-surface:");
  expect(tokens).toContain("--muted:");
  expect(tokens).toContain("--tray-height:");
  expect(tokens).toContain("--title-size:");
  expect(tokens).toContain("--dock: #05080a");
  expect(tokens).toContain("--rail:");
  expect(tokens).toContain("--outcome-won:");
  expect(tokens).toContain("--font-display:");
  expect(tokens).toContain("color: var(--cream)");
  const layouts = readFileSync(join(process.cwd(), "src/ui/skins/classic/layouts.css"), "utf8");
  expect(layouts).toContain("background: var(--dock)");
  expect(layouts).toContain("min-height: var(--control-height)");
  expect(layouts).toContain("border-radius: var(--radius)");
  expect(layouts).not.toContain("#10241f");
  expect(tokens).toContain("pointer-events: none");
  const table = readFileSync(join(process.cwd(), "src/ui/skins/classic/table.css"), "utf8");
  expect(table).not.toContain("outline: 8px solid var(--rail)");
  expect(table).not.toContain("0 0 0 9px var(--rail)");
  expect(table).toContain("pointer-events: none");
  expect(layouts).toContain(".deal-actions.next-round-row");
});

test("classic CSS files keep exclusive ownership", () => {
  const tokens = readFileSync(join(process.cwd(), "src/ui/skins/classic/tokens.css"), "utf8");
  const layouts = readFileSync(join(process.cwd(), "src/ui/skins/classic/layouts.css"), "utf8");
  const table = readFileSync(join(process.cwd(), "src/ui/skins/classic/table.css"), "utf8");
  const board = readFileSync(join(process.cwd(), "src/ui/skins/classic/board.css"), "utf8");
  const home = readFileSync(join(process.cwd(), "src/ui/skins/classic/home.css"), "utf8");
  const invite = readFileSync(join(process.cwd(), "src/ui/skins/classic/invite.css"), "utf8");
  const welcome = readFileSync(join(process.cwd(), "src/ui/skins/classic/welcome-celebration.css"), "utf8");
  expect(tokens).not.toMatch(/!important/);
  expect(home).not.toMatch(/!important/);
  expect(board).not.toMatch(/!important/);
  expect(table).not.toMatch(/!important/);
  expect(layouts).not.toMatch(/!important/);
  expect(invite).not.toMatch(/!important/);
  expect(welcome).not.toMatch(/!important/);
  expect(tokens).not.toMatch(/\.home-heading|\.dealer-position|\.player-box-stage/);
  expect(home).not.toMatch(/\.player-box-stage|\.dealer-list\.dealer-positions|\[data-table-board="BLACKJACK|\.invite-mask|\.waiting-pulse|\.dealer-position/);
  expect(board).not.toMatch(/\.home-heading|\.home-table-card|\.home-resume/);
  expect(board).not.toMatch(/\.felt-plaque|\.player-box-stage|\.dealer-list\.dealer-positions/);
  expect(home).toContain(".home-heading");
  expect(home).toContain(".create-heading");
  expect(invite).toContain(".invite-mask");
  expect(board).toContain(".cloth-name");
  const blackjack = readFileSync(join(process.cwd(), "src/ui/skins/classic/blackjack-classic.css"), "utf8");
  expect(blackjack).toContain(".bj-player");
  expect(blackjack).toContain(".bj-ledger");
  expect(blackjack).not.toMatch(/!important/);
});
